PaginaWeb1/Models/DatosContacto.cs
namespace PaginaWeb1.Models
{
    public class DatosContacto
    {
        public String Nombre { get; set; }

        public String Correo { get; set; }

        public String Comentario { get; set; }



    }
}

PaginaWeb1/Models/ErrorViewModel.cs
namespace PaginaWeb1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PaginaWeb1/Controllers/ContactosController.cs
using Microsoft.AspNetCore.Mvc;
using PaginaWeb1.Models;
namespace PaginaWeb1.Controllers
{
    public class ContactosController : Controller
    {
        List<DatosContacto> datos = new List<DatosContacto>() {

            new DatosContacto() { Correo="rmonge@ui.edu",
                Nombre="Ricardo" },
            new DatosContacto() { Correo="karim@ui.edu",
                Nombre="Karim" },
            new DatosContacto() { Correo="fabio@ui.edu",
                Nombre="Fabiola" },
        };
        public IActionResult Index()
        {
            return View(datos);
        }
    }
}

PaginaWeb1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PaginaWeb1.Models;
using System.Diagnostics;

namespace PaginaWeb1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Contactenos() {
            //DatosContacto dc = new DatosContacto();
            //dc.Nombre = "Adriana";
            //dc.Correo = "a@upi.ac.cr";
            //dc.Comentario = "Es muy chiva";
            return View();

        }
        [HttpPost] /*Atributo del metodo, solo es para cuando envio el formulario */
        public IActionResult Contactenos(DatosContacto DC) {
            DC.Comentario = "Comentario generico";
            return View("ContactenosGracias", DC);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PaginaWeb1/Views/Contactos/Index.cshtml
@model IEnumerable<PaginaWeb1.Models.DatosContacto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Correo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comentario)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Correo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comentario)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

PaginaWeb1/Views/Home/Contactenos.cshtml
@model PaginaWeb1.Models.DatosContacto
@{
    ViewData["Title"] = "Contactenos";
}

<h1>Formulario de contacto</h1>
<p>
    Por favor, deje sus datos personales y lo contactamos
</p>

<form asp-action="Contactenos">
    <div class="mb-3">
    <label for="correo" 
        class="form-label">Correo electronico</label>
    <input type="email" class="form-control" 
    id="correo" name="Correo">
  
  </div>
   <div class="mb-3">
    <label for="nombre" 
        class="form-label">Nombre completo</label>
    <input type="text" class="form-control" 
    id="nombre" name="Nombre"> 
  
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

PaginaWeb1/Views/Home/ContactenosGracias.cshtml
@model PaginaWeb1.Models.DatosContacto
@{
    ViewData["Title"] = "Contactenos";
}

<h1>Formulario de contacto-gracias por contactarnos</h1>
<h2>@Model.Nombre</h2>
<p>Correo:
    @Model.Correo

</p>
<hr />
<a asp-action="Index">Regresar al principal</a>

PaginaWeb1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h2>Bienvenido a mi sitio</h2>
<p>
    Por favor utilice los comandos de la barra superior para navegar este sitio
    <a asp-action="Contactenos">Ir a formulario de contacto </a>
</p>
<a asp-action="Index" asp-controller="Contactos">Listado de contactos</a>
</p>

PaginaWeb1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PaginaWeb1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PaginaWeb1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PaginaWeb1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PaginaWeb1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>